apiVersion: v2
name: clomonitor
description: CLOMonitor is a tool that periodically checks open source projects repositories to verify they meet certain project health best practices
type: application
version: 1.0.0
appVersion: 1.0.0
kubeVersion: ">= 1.19.0-0"
keywords:
  - cncf
  - lint
maintainers:
  - name: Sergio
    email: tegioz@icloud.com
  - name: Cintia
    email: cynthiasg@icloud.com
dependencies:
  - name: postgresql
    version: 8.2.1
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
