---
version: 2

multi-ecosystem-groups:
  backend:
    schedule:
      interval: "monthly"
  frontend:
    schedule:
      interval: "monthly"
  infra:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    ignore:
      - dependency-name: "octorust"
      - dependency-name: "resvg"
      - dependency-name: "tiny-skia"
      - dependency-name: "usvg"
    multi-ecosystem-group: "backend"
    patterns:
      - "*"

  - package-ecosystem: "docker"
    directory: "/clomonitor-apiserver"
    ignore:
      - dependency-name: "node"
        versions:
          [
            "19-alpine3.19",
            "20-alpine3.19",
            "21-alpine3.19",
            "22-alpine3.19",
            "22-alpine3.20",
            "23-alpine3.21",
          ]
    multi-ecosystem-group: "infra"
    patterns:
      - "*"

  - package-ecosystem: "docker"
    directory: "/clomonitor-archiver"
    multi-ecosystem-group: "infra"
    patterns:
      - "*"

  - package-ecosystem: "docker"
    directory: "/clomonitor-linter"
    multi-ecosystem-group: "infra"
    patterns:
      - "*"

  - package-ecosystem: "docker"
    directory: "/clomonitor-notifier"
    multi-ecosystem-group: "infra"
    patterns:
      - "*"

  - package-ecosystem: "docker"
    directory: "/clomonitor-registrar"
    multi-ecosystem-group: "infra"
    patterns:
      - "*"

  - package-ecosystem: "docker"
    directory: "/clomonitor-tracker"
    multi-ecosystem-group: "infra"
    patterns:
      - "*"

  - package-ecosystem: "docker"
    directory: "/database/migrations"
    multi-ecosystem-group: "infra"
    patterns:
      - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "infra"
    patterns:
      - "*"

  - package-ecosystem: "npm"
    directory: "/web"
    ignore:
      - dependency-name: "bootstrap"
        versions: ["5.2.x"]
      - dependency-name: "postcss"
    multi-ecosystem-group: "frontend"
    patterns:
      - "*"
