[advisories]
vulnerability = "warn"
ignore = []

[bans]
multiple-versions = "allow"

[licenses]
allow-osi-fsf-free = "either"
allow = [
    "MPL-2.0",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "tag"
allow-git = [
    "https://github.com/djc/askama.git",
    "https://github.com/graphql-rust/graphql-client.git"
]
