apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}dbmigrator-upgrade
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      restartPolicy: Never
      initContainers:
      - name: check-db-ready
        image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
          - name: PGHOST
            value: {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
          - name: PGPORT
            value: "{{ .Values.db.port }}"
        command: ['sh', '-c', 'until pg_isready; do echo waiting for database; sleep 2; done;']
      containers:
      - name: dbmigrator
        image: {{ .Values.dbmigrator.job.image.repository }}:{{ .Values.imageTag | default (printf "v%s" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
          - name: TERN_CONF
            value: {{ .Values.configDir }}/tern.conf
        volumeMounts:
          - name: dbmigrator-config
            mountPath: {{ .Values.configDir }}
            readOnly: true
        command: ["./migrate.sh"]
      volumes:
      - name: dbmigrator-config
        secret:
          secretName: {{ include "chart.resourceNamePrefix" . }}dbmigrator-config
