{{- if .Values.notifier.enabled -}}
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}notifier
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: Never
          initContainers:
            - {{- include "chart.checkDbIsReadyInitContainer" . | nindent 14 }}
          containers:
            - name: notifier
              image: {{ .Values.notifier.cronjob.image.repository }}:{{ .Values.imageTag | default (printf "v%s" .Chart.AppVersion) }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              resources:
                {{- toYaml .Values.notifier.cronjob.resources | nindent 16 }}
              volumeMounts:
                - name: notifier-config
                  mountPath: {{ .Values.configDir | quote }}
                  readOnly: true
              command: ['clomonitor-notifier', '-c', '{{ .Values.configDir }}/notifier.yaml']
          volumes:
            - name: notifier-config
              secret:
                secretName: {{ include "chart.resourceNamePrefix" . }}notifier-config
{{- end }}
