apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}tracker-config
type: Opaque
stringData:
  tracker.yaml: |-
    db:
      host: {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
      port: {{ .Values.db.port }}
      dbname: {{ .Values.db.dbname }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    creds:
      githubTokens:
        {{- toYaml .Values.creds.githubTokens | nindent 8 }}
    log:
      format: {{ .Values.log.format }}
    tracker:
      concurrency: {{ .Values.tracker.concurrency }}
    {{- if or .Values.runner.afdocs.enabled .Values.runner.scorecard.enabled }}
    runner:
      {{- if .Values.runner.afdocs.enabled }}
      afdocsUrl: http://{{ include "chart.resourceNamePrefix" . }}runner-afdocs:{{ .Values.runner.afdocs.service.port }}
      {{- end }}
      {{- if .Values.runner.scorecard.enabled }}
      scorecardUrl: http://{{ include "chart.resourceNamePrefix" . }}runner-scorecard:{{ .Values.runner.scorecard.service.port }}
      {{- end }}
    {{- end }}
