{
 "title": "CLOMonitor",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful requests processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(clomonitor_apiserver_http_request_duration_count{status=\"200\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Successful requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(clomonitor_apiserver_http_request_duration_count{status=\"200\"}[$__interval])) / sum(rate(clomonitor_apiserver_http_request_duration_count{}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "Failed requests processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(clomonitor_apiserver_http_request_duration_count{status!=\"200\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Last day requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(clomonitor_apiserver_http_request_duration_count{}[$__rate_interval]))",
     "legendFormat": "Requests in 15m"
    }
   ]
  },
  {
   "title": "Last month requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(clomonitor_apiserver_http_request_duration_count{}[$__rate_interval]))",
     "legendFormat": "Daily requests"
    }
   ]
  },
  { "title": "API latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "API average latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(clomonitor_apiserver_http_request_duration_sum{status=\"200\"}[$__rate_interval])) / sum(rate(clomonitor_apiserver_http_request_duration_count{status=\"200\"}[$__rate_interval]))",
     "legendFormat": "API average latency"
    }
   ]
  },
  { "title": "API requests rate (per second)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Successful requests rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(clomonitor_apiserver_http_request_duration_count{status=\"200\"}[$__rate_interval])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Failed requests rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(clomonitor_apiserver_http_request_duration_count{status=\"500\"}[$__rate_interval])) by (path)"
    }
   ]
  },
  {
   "title": "API requests duration (in seconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Successful requests duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(clomonitor_apiserver_http_request_duration_bucket{status=\"200\"}[$__rate_interval])) by (path, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Failed requests duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(clomonitor_apiserver_http_request_duration_bucket{status=\"500\"}[$__rate_interval])) by (path, le))"
    }
   ]
  },
  {
   "title": "Successful requests duration (p75)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(clomonitor_apiserver_http_request_duration_bucket{status=\"200\"}[$__rate_interval])) by (path, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Failed requests duration (p75)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(clomonitor_apiserver_http_request_duration_bucket{status=\"500\"}[$__rate_interval])) by (path, le))"
    }
   ]
  },
  {
   "title": "Successful requests duration (p50)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(clomonitor_apiserver_http_request_duration_bucket{status=\"200\"}[$__rate_interval])) by (path, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Failed requests duration (p50)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(clomonitor_apiserver_http_request_duration_bucket{status=\"500\"}[$__rate_interval])) by (path, le))"
    }
   ]
  }
 ]
}